#define LAYER_STATE_8BIT
#define NO_ACTION_TAPPING
#define NO_ACTION_ONESHOT
#define NO_USB_STARTUP_CHECK
#define NO_ACTION_LAYER

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define USB_DEFAULT_BUFFER_CAPACITY 1
