# Reduce code size
USE_PROCESS_STACKSIZE    = 0x1E0
USE_EXCEPTIONS_STACKSIZE = 0xE0
LTO_ENABLE = yes

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no